// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "/abhi.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
    "/shah.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
    "/abhi.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
    "/shah.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
    "/abhi.jpg?auto=compress&cs=tinysrgb&w=1200",
        phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
    "/abhi.jpg?auto=compress&cs=tinysrgb&w=1200",
        phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
    "/abhi.jpg?auto=compress&cs=tinysrgb&w=1200",    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
    "/anan.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
    "/jigy.jpg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Aditya Maurya","Vanshika Gupta", "Vishal Singh"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Shahnawaz Ahmad", "Abhishek Singh"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Anantesh Chauhan", "Dipanshu Sahu"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: [ "Vanshika Gupta","Sakshi Singh","Aman Kumar Maurya"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Devansh Gupta", "Shriyanshi Shrivastava"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Shahnawaz Ahmad", "Abhishek Singh"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Sakshi Singh", "Rishita Shrivastava"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Aditya Maurya", "Devansh Gupta"],
  },
  {
    id: 9,
    name: "Computer",
    teachers: ["Aditya Maurya","Abhishek Singh", "Jigyasu Saini"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: [ "Rajita Singh","Anurag Singh Chauhan"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8, 1, 8, 0),
    end: new Date(2024, 8, 1, 8, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8, 1, 9, 0),
    end: new Date(2024, 8,1, 9, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8, 2, 8, 0),
    end: new Date(2024, 8, 2, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 8, 2, 9, 0),
    end: new Date(2024, 8, 2, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 8, 2, 10, 0),
    end: new Date(2024, 8, 2, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 8, 2, 11, 0),
    end: new Date(2024, 8, 2, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024,8, 9, 13, 0),
    end: new Date(2024,8, 9, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 8, 9, 14, 0),
    end: new Date(2024,8, 9, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 8,10, 9, 0),
    end: new Date(2024, 8,10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 8,3, 10, 0),
    end: new Date(2024,8,3, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 8,11, 11, 0),
    end: new Date(2024, 8,11, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 8,3, 14, 0),
    end: new Date(2024, 8,3, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8,4, 8, 0),
    end: new Date(2024, 8,4, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 8,13, 10, 0),
    end: new Date(2024, 8, 13, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 8, 12, 13, 0),
    end: new Date(2024, 8, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 8,4, 9, 0),
    end: new Date(2024, 8,4, 9, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 8, 5, 9, 0),
    end: new Date(2024, 8, 5, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 8, 5, 10, 0),
    end: new Date(2024, 8, 5, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 8, 5, 11, 0),
    end: new Date(2024, 8, 5, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 8, 12, 14, 0),
    end: new Date(2024, 8, 12, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 8, 13, 8, 0),
    end: new Date(2024, 8, 13, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 8, 6, 9, 0),
    end: new Date(2024, 8, 6, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 8, 6, 11, 0),
    end: new Date(2024, 8, 6, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 8, 6, 13, 0),
    end: new Date(2024, 8, 6, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 8, 6, 14, 0),
    end: new Date(2024, 8, 6, 14, 45),
  },
];

export const messagesData = [
  {
      id: 1,
      sender: "Mr. Smith",
      date: "2024-09-01",
      subject: "Welcome to the new school year",
      preview: "Dear students, welcome back! We have some exciting plans for this year...",
      content: "Dear students, welcome back! We have some exciting plans for this year, including new extracurricular activities and updated curriculum. Stay tuned for more details."
  },
  {
      id: 2,
      sender: "Ms. Johnson",
      date: "2024-08-25",
      subject: "Important: Science Lab Safety Rules",
      preview: "Please make sure to review the new safety rules for the science lab. It's crucial to follow these guidelines...",
      content: "Please make sure to review the new safety rules for the science lab. It's crucial to follow these guidelines to ensure everyone's safety. The rules are posted on the school website."
  },
  // Add more messages as needed
];
export const attendanceData = [
  {
    id: 1,
    name: "John Doe",
    class: "1B",
    totalDays: 180,
    daysPresent: 170,
    presentPercent: 94.4, // (170/180) * 100
    comments: "Excellent attendance throughout the year.",
  },
  {
    id: 2,
    name: "Jane Doe",
    class: "5A",
    totalDays: 180,
    daysPresent: 165,
    presentPercent: 91.7, // (165/180) * 100
    comments: "Missed some days due to illness.",
  },
  {
    id: 3,
    name: "Mike Geller",
    class: "5A",
    totalDays: 180,
    daysPresent: 160,
    presentPercent: 88.9, // (160/180) * 100
    comments: "Regularly late but has good attendance overall.",
  },
  {
    id: 4,
    name: "Jay French",
    class: "5A",
    totalDays: 180,
    daysPresent: 150,
    presentPercent: 83.3, // (150/180) * 100
    comments: "Had frequent absences, needs improvement.",
  },
  {
    id: 5,
    name: "Jane Smith",
    class: "5A",
    totalDays: 180,
    daysPresent: 175,
    presentPercent: 97.2, // (175/180) * 100
    comments: "Excellent attendance and punctuality.",
  },
  {
    id: 6,
    name: "Anna Santiago",
    class: "5A",
    totalDays: 180,
    daysPresent: 172,
    presentPercent: 95.6, // (172/180) * 100
    comments: "Consistently present and engaged in class.",
  },
  {
    id: 7,
    name: "Allen Black",
    class: "5A",
    totalDays: 180,
    daysPresent: 168,
    presentPercent: 93.3, // (168/180) * 100
    comments: "Good attendance, missed a few due to family reasons.",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    class: "5A",
    totalDays: 180,
    daysPresent: 160,
    presentPercent: 88.9, // (160/180) * 100
    comments: "Needs to improve attendance; missed several classes.",
  },
  {
    id: 9,
    name: "Derek Briggs",
    class: "5A",
    totalDays: 180,
    daysPresent: 155,
    presentPercent: 86.1, // (155/180) * 100
    comments: "Attendance issues; missed classes without valid reasons.",
  },
  {
    id: 10,
    name: "John Glover",
    class: "5A",
    totalDays: 180,
    daysPresent: 170,
    presentPercent: 94.4, // (170/180) * 100
    comments: "Good attendance; participated actively in class.",
  },
];